name: Drive Monitor

on:
  schedule:
    # 매일 UTC 기준 12:00에 실행 (한국 시간 21:00)
    - cron: '0 12 * * *'
  workflow_dispatch:  # 수동 실행도 가능하게 설정

permissions:
  contents: read
  actions: read

jobs:
  monitor_drive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create data directory
      run: mkdir -p data

    - name: Setup Google credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > data/credentials.json

    - name: Setup environment variables
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
        PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        CHECK_INTERVAL: "300"
      run: |
        echo "PINECONE_API_KEY=$PINECONE_API_KEY" > .env
        echo "PINECONE_ENVIRONMENT=$PINECONE_ENVIRONMENT" >> .env
        echo "PINECONE_INDEX=$PINECONE_INDEX" >> .env
        echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
        echo "DRIVE_FOLDER_ID=$DRIVE_FOLDER_ID" >> .env
        echo "CHECK_INTERVAL=$CHECK_INTERVAL" >> .env

    - name: Restore checkpoint file
      uses: actions/download-artifact@179bc3b6236dca0fbff5ce4e23d6b238f5f91856
      with:
        name: checkpoint-file
        path: data/
      continue-on-error: true

    - name: Save checkpoint file
      uses: actions/upload-artifact@7a73a45fdc3d2a603c3838a9bc6e4d6f70e7796d
      with:
        name: checkpoint-file
        path: data/drive_checkpoint.json
        retention-days: 7

    - name: Save logs
      uses: actions/upload-artifact@7a73a45fdc3d2a603c3838a9bc6e4d6f70e7796d
      with:
        name: logs
        path: data/drive_monitor.log
        retention-days: 1

